---
title: "Shiny_Final"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r global, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(tidyverse)
library(sf)
library(tigris)
library(mapview)
library(leaflet)
library(censusapi)
library(gtools)

usa_pums_pop <- readRDS("usa_pums_pop.rds")

```


Inputs {.sidebar}
-------------------------------------

```{r}
checkboxGroupInput(
  inputId = "year",
  label = "Year: ",
  choices = 2017:2020,
  selected = 2020
)
```

```{r}
selectInput(
  inputId = "class",
  label = "Energy Type: ",
  choices = c("Residential Electricity" = "Elec- Residential",
              "Commercial Electricity" = "Elec- Commercial", 
              "Residential Gas" = "Gas- Residential",
              "Commercial Gas" = "Gas- Commercial"),
  selected = "Residential Electricity"
)
```


Column
-------------------------------------

### USA Map

```{r}
leafletOutput("map")
```

```{r, context = "server"}
observeEvent({
  input$year
  input$class},
  { 
couple_pal <- colorNumeric(
  palette = "Blues",
  domain = 
    c(0,5)
)

output$map <- renderLeaflet({
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = usa_pums_pop, 
    fillColor = ~couple_pal (percent),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1,
    label = ~paste0(
      round(percent*100)/100,
      "% same-sex couples"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = usa_pums_pop,
    pal = couple_pal,
    values = 0:5,
    title = "% same-sex relationships"
  )
})

})

```


Column
-------------------------------------

<!-- ### ZCTA consumption -->

<!-- ```{r} -->
<!-- plotlyOutput("plot") -->
<!-- ``` -->

<!-- ```{r, context = "server"} -->
<!-- observeEvent({ -->
<!--   input$year -->
<!--   input$class}, { # wrapper to make it listen to changes in input$year and update the display accordingly -->
<!--   # Identify correct label for energy type -->
<!--   class <- input$class -->
<!--   if (class == "Elec- Residential") class = "Residential Electricity" -->
<!--   else if (class == "Elec- Commercial") class = "Commercial Electricity" -->
<!--   else if (class == "Gas- Residential") class = "Residential Gas" -->
<!--   else if (class == "Gas- Commercial") class = "Commercial Gas" -->

<!--   chart <- us_pums_IRC %>%  -->
<!--   group_by(income, race) %>%  -->
<!--   summarize(estimate = sum(PWGTP)) %>%  -->
<!--   rbind(us_race_total) %>%   -->
<!--   ggplot() + -->
<!--   geom_bar( -->
<!--     aes( -->
<!--       x = income %>% factor(levels = rev(c("Total", mixedsort(order)))), -->
<!--       y = estimate, -->
<!--       fill = race  -->
<!--     ), -->
<!--     stat = "identity", -->
<!--     position = "fill" -->
<!--   ) + -->
<!--   labs( -->
<!--     x = "Household income", -->
<!--     y = "Number of households", -->
<!--     title = "US personal income by race: Individuals in same-sex relationships", -->
<!--     fill = "Race" -->
<!--   ) + -->
<!--   coord_flip() + -->
<!--   theme( -->
<!--     legend.position = "bottom", -->
<!--     legend.direction = "vertical" -->
<!--   )  + -->
<!--   guides( -->
<!--     fill = guide_legend( -->
<!--       reverse = T -->
<!--     ) -->
<!--   ) -->

<!--   output$plot <- renderPlotly({ # wrapper to keep output dynamic  -->
<!--     chart %>%  -->
<!--       ggplotly() %>%  -->
<!--       config(displayModeBar = F) -->
<!--   }) -->

<!-- }, -->
<!--   ignoreNULL = T) -->

<!-- ``` -->